### ISSUE TITLE
Tests fail on PRs from forked repos

### ISSUE THREAD

**Issue by rhandberg** [SNflows/flows#33]
**Describe the bug**
Tests fail on pull requests from forked repos. This is because repository "secrets" are not passed to Actions for pull requests from forked repos.

**To Reproduce**
See e.g. https://github.com/rhandberg/flows/actions/runs/874418844

**Expected behavior**
Tests should pass.

**Desktop**
 - OS: Any
 - Python version: Any
 - Version: 0.6.x

**Comment by emirkmo** [comment]
I see two hacks:

1.  I can set secrets in my own repo to mirror this one.
2. I can create a branch in this repo, merge mine into that branch Without tests (just basic linting), and then we run a PR within the repo.
... 
3. Change tests to not need secrets.

**Comment by emirkmo** [comment]
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

I found the solution I think, going to test..
